# Generated by Django 3.2.12 on 2022-05-31 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_user_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienttable',
            name='medical_history',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
