# Generated by Django 3.2.12 on 2022-05-31 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_clienttable_medical_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='assesment',
            name='presenting_complaints',
            field=models.TextField(blank=True, null=True),
        ),
    ]
