# Generated by Django 3.2.12 on 2022-05-31 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_assesment_presenting_complaints'),
    ]

    operations = [
        migrations.AddField(
            model_name='assesment',
            name='test_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assesment',
            name='test_results',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
