# Generated by Django 3.2.12 on 2022-06-20 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20220531_1013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assesment',
            old_name='test_score',
            new_name='dev_months',
        ),
        migrations.AddField(
            model_name='assesment',
            name='dev_years',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assesment',
            name='qutient',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
