# Generated by Django 3.2.12 on 2022-06-20 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20220620_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assesment',
            name='dev_months',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assesment',
            name='dev_years',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assesment',
            name='qutient',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
