# Generated by Django 3.2.12 on 2022-06-21 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20220620_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assesment',
            name='qutient',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
