# Generated by Django 3.2.12 on 2022-06-21 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_assesment_qutient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assesment',
            name='qutient',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
